name: 'Frontend CI/CD'

on:
  push:
    branches: [main]
    paths:
      - 'ui/**'

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          version: ${{ matrix.node_version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run style:all

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: ./build

  # CD:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: production
  #         path: ./build

  #     - name: Deploying Project to Amplify
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AMPLIFY_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_AMPLIFY_SECRET_ACCESS_KEY }}
  #         REACT_APP_TEST: ${{ secrets.REACT_APP_TEST }}
  #       working-directory: ./ui
  #       run: |
  #         bash scripts/init.sh
  #         amplify publish --yes
